### PR TITLE
Fixing RN handler

### PR DESCRIPTION
**Pull request by filipi87**
- Fixing to be able to send more than one video from RN.

They are currently trying to use the mid when the negotiation is not completed yet. 

In this case, they are receiving null as the mid value, instead of the value itself. When we try to send a second video track, for instance the video from getDisplayMedia, we stop to send the first one. 

More details about mid: https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpTransceiver/mid

- Fixing to be able to send video from iOS when using encodings, which we basically do for the simulcast.

In order to make It work, we are changing the `ReactNativeUnifiedPlan` handler to behave in a similar way as the Safari12 handler. More details [here](https://github.com/versatica/mediasoup-client/blob/8f80c6a853bba2801f102c9d8d276a08aa8ad297/src/handlers/Safari12.ts#L292).

The idea is to submit this same PR to the mediasoup-client upstream, so we can keep using the official version of the library.

### CODE REVIEW

**Comment by kompfner** [comment]
Is the following the right understanding of this change?
* The mediasoup team assumed that the new version of `react-native-webrtc` (the one with Unified Plan support) would work like Chrome 74+ (and so they made the ReactNativeUnifiedPlan handler identical to the Chrome74 handler), but in reality it behaves more like Safari 12+.
* You fixed the problem by simply replacing ReactNativeUnifiedPlan handler's contents with the Safari12 handler's contents (or did you have to do more nuanced surgery?)

**Comment by filipi87** [comment]
Hi @kompfner, yep, that was basically It. But I have not changed all the methods, I have just changed the send() method, since the issue was when I was trying to send video from iOS.

I intend to open an issue on mediasoup-client, and explain what we have changed, so they can decide in the future if there is a better way to fix It.

**Comment by mattieruth** [comment]
just randomly saw this still waiting on my review... is this still a thing i should look at?

**Comment by filipi87** [comment]
> just randomly saw this still waiting on my review... is this still a thing i should look at?

Hi @mattieruth, nops, nothing to do, we have applied a patch inside `pluot-core`. It is just here so we can be aware about what we have changed. But maybe I can even close this PR.

**Comment by aconchillo** [comment]
@filipi87 I believe we can close this, right?

**Comment by filipi87** [comment]
> @filipi87 I believe we can close this, right?

We can. 👍

**Pull request closed without merging**
